"""
Excavation state machine states.
"""

from enum import Enum


class ExcavationState(str, Enum):
    IDLE = "IDLE"
    SELF_CHECK = "SELF_CHECK"
    APPROACH_DIG_ZONE = "APPROACH_DIG_ZONE"
    DIG_ZONE_REACHABILITY_CHECK = "DIG_ZONE_REACHABILITY_CHECK"
    ALIGN = "ALIGN"
    BUCKET_POSITIONING = "BUCKET_POSITIONING"
    SOIL_CONTACT = "SOIL_CONTACT"
    PENETRATION = "PENETRATION"
    SCOOP = "SCOOP"
    LOAD_VERIFICATION = "LOAD_VERIFICATION"
    LIFT = "LIFT"
    LOAD_RECHECK = "LOAD_RECHECK"
    TRANSPORT = "TRANSPORT"
    DUMP_POSITIONING = "DUMP_POSITIONING"
    DUMP = "DUMP"
    EMPTY_VERIFICATION = "EMPTY_VERIFICATION"
    RESET = "RESET"
    NEXT_SCOOP = "NEXT_SCOOP"
    RECOVERY = "RECOVERY"
    FAULT = "FAULT"
    EMERGENCY_STOP = "EMERGENCY_STOP"
